objects/Class_Student__c.object
<CustomObject>
    <label>Class Student</label>
    <nameField>
        <label>Class Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ROLL_NO__c</fullName>
        <displayFormat>CR-{0000}</displayFormat>
        <label>ROLL NO</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>PERSONAL_GMAIL_ID__c</fullName>
        <label>PERSONAL GMAIL-ID</label>
        <type>Email</type>
    </fields>
</CustomObject>

classes/apexclassone.cls
public class apexclassone {
	public static void method1()
    {
        list<Class_Student__c>newstudent = new list<Class_Student__c>();
       	newstudent = [select id,name,Gender__c,ROLL_NO__c from Class_Student__c where PERSONAL_GMAIL_ID__c = 'jayachandra.n@svce.edu.in' ];
        for(Class_Student__c k : newstudent)
        system.debug('the student info is'+k);
        list<Class_Student__c>newstudent2 = new list<Class_Student__c>();
        newstudent2 = [select id,name,Gender__c,ROLL_NO__c from Class_Student__c where PERSONAL_GMAIL_ID__c = 'alluhemanth01@gmail.com' ];
        for(Class_Student__c k : newstudent2)
        system.debug('the student info is'+k);
        
    }
}